version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 14
