name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hassfest:
    name: hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: home-assistant/actions/hassfest@868e6cb4607727d764341a158d98872cd63fa658

  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: hacs/action@main
        with:
          category: integration

  lint:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.14.2"
      - run: pip install ruff
      - run: ruff check custom_components/
      - run: ruff format --check custom_components/

